-- DDL generated by Postico 1.5.3

-- Table Definition ----------------------------------------------

CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    owner_id TEXT,
    project_name text UNIQUE,
    project_description text,
    business_name text,
    business_description text,
    opt_lock integer,
    creation_date timestamp without time zone DEFAULT now(),
    status text
);

CREATE TABLE skills (
    id SERIAL PRIMARY KEY,
    skill_name text UNIQUE,
    description text
);

INSERT INTO skills VALUES
    (1, 'frontend', null),
    (2, 'backend', null),
    (3, 'full stack', null),
    (4, 'design', null);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    token_id text,
    first_name text,
    last_name text,
    email text,
    phone_number text,
    status text,
    bio text,
    opt_lock integer,
    type text,
    created timestamp without time zone DEFAULT now(),
    updated timestamp
);

CREATE TABLE owners (
    id SERIAL PRIMARY KEY,
    user_id serial,
    project_id serial,
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE volunteers
(
    user_id bigint NOT NULL,
    project_id bigint NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE CASCADE ON UPDATE RESTRICT
);
